import 'reflect-metadata';

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { DataSource } from 'typeorm';
import { dataSourceOptions } from '../src/database/data-source';

/**
 * Writes docs/ai/schema-inventory.md: every table, its columns, and the migration that
 * created it.
 *
 *   DB_*=… npm run schema:inventory      # against a database migrated to the head
 *
 * It exists so a task is not written for work already shipped (it was agreed after the
 * QREC0a duplication and never built until QFIX-BASELINE). Read from a migrated database
 * rather than parsed out of the migrations, because the columns a table has today are
 * the sum of every later ALTER — only the database knows that sum for certain. The
 * creating migration is found by name in the migration sources; a table no migration
 * creates by name is listed as such rather than guessed at.
 */
async function main() {
  const ds = await new DataSource(dataSourceOptions(process.env, { appRole: null })).initialize();
  try {
    const [{ head, applied }] = await ds.query(
      `SELECT (SELECT name FROM migrations ORDER BY id DESC LIMIT 1) AS head, (SELECT count(*)::int FROM migrations) AS applied`,
    );
    const columns: { table: string; column: string; type: string; nullable: string; dflt: string | null }[] = await ds.query(`
      SELECT c.table_name AS "table", c.column_name AS "column",
             CASE WHEN c.data_type = 'ARRAY' THEN replace(c.udt_name, '_', '') || '[]'
                  WHEN c.data_type = 'USER-DEFINED' THEN c.udt_name ELSE c.data_type END AS "type",
             c.is_nullable AS nullable, c.column_default AS dflt
        FROM information_schema.columns c
        JOIN pg_class k ON k.relname = c.table_name
        JOIN pg_namespace n ON n.oid = k.relnamespace AND n.nspname = c.table_schema
       WHERE c.table_schema = 'public' AND k.relkind IN ('r', 'p') AND NOT k.relispartition
         AND c.table_name <> 'migrations'
       ORDER BY c.table_name, c.ordinal_position`);

    const dir = join(__dirname, '..', 'src', 'database', 'migrations');
    const sources = readdirSync(dir).filter((f) => f.endsWith('.ts')).sort()
      .map((f) => ({ file: f, text: readFileSync(join(dir, f), 'utf8') }));
    const createdBy = (table: string) => sources.find((s) =>
      new RegExp(`CREATE TABLE (IF NOT EXISTS )?"?${table}"?[\\s(]`).test(s.text))?.file ?? null;

    const tables = [...new Set(columns.map((c) => c.table))];
    const lines = [
      '# Schema inventory',
      '',
      'Generated by `npm run schema:inventory` from a database migrated to the head — do not edit by hand;',
      're-run it after a migration lands. Every table, its columns as they are now (every later `ALTER`',
      'included), and the migration that created it. Partitions of a partitioned table are not listed',
      'separately.',
      '',
      `Head: \`${head}\` (${applied} migrations). Tables: ${tables.length}.`,
      '',
      '| Table | Created by | Columns |',
      '|---|---|---|',
      ...tables.map((t) => `| [\`${t}\`](#${t.replace(/_/g, '_')}) | ${createdBy(t) ? `\`${createdBy(t)}\`` : '_not created by name in any migration_'} | ${columns.filter((c) => c.table === t).length} |`),
      '',
    ];
    for (const t of tables) {
      lines.push(`## ${t}`, '', `Created by ${createdBy(t) ? `\`${createdBy(t)}\`` : '_no migration by name_'}.`, '');
      lines.push('| Column | Type | Null | Default |', '|---|---|---|---|');
      for (const c of columns.filter((x) => x.table === t)) {
        const dflt = c.dflt ? `\`${c.dflt.replace(/\|/g, '\\|')}\`` : '';
        lines.push(`| \`${c.column}\` | ${c.type} | ${c.nullable === 'YES' ? 'yes' : ''} | ${dflt} |`);
      }
      lines.push('');
    }
    const out = join(__dirname, '..', 'docs', 'ai', 'schema-inventory.md');
    writeFileSync(out, lines.join('\n'), 'utf8');
    // eslint-disable-next-line no-console
    console.log(`Wrote ${out}: ${tables.length} tables, ${columns.length} columns, head ${head}.`);
  } finally {
    await ds.destroy();
  }
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
